Milestone 3 - Friendships v2
jrai0792/ror-social-scaffold pull request #3
Opened 2020-12-17 14:13 UTC by jrai0792

- In this milestone, have added mutual friendship logic.

2020-12-17 19:21 UTC, lekegitrepo requested changes
## Status: Changes Required! :recycle:
### Hi @jrai0792 :clap: :clap:
#### You have done a good job so far :+1: The friendship model works as expected(it creates a friend and inverse friend in the friendship table. However, you need to fix/implement a few requirements before this project can be approved. Check my comments below :point_down:

#### PostsController:
- The index action method should contain code that retrieves data not create one.
```
def index
    @post = Post.new
    timeline_posts
  end
```
`@post = Post.new` should not be in the index action method instead you can create tje `new` action method
```
def new
    @post = Post.new
  end
```

#### Tests:
- _One of the tests is failing :point_down:_ 

![Screenshot from 2020-12-17 12-55-41](https://user-images.githubusercontent.com/48312803/102531005-519d3b00-4067-11eb-8f80-7a7d80ee3449.png)

#### Logic in the view:
- _There should be NO application logic in the views. Everything connected with data processing should be encapsulated in models and used in controllers._

- _View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)_

- _There should be absolutely NO logic in views. >Views are only for displaying information that became available to it from its corresponding controller not generating it. **Check these resources details**_
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

### Optional:
- _You can read about `n+1` and improve your queries if there are `n + 1` queries in index views [Recommended article](https://medium.com/@bretdoucette/n-1-queries-and-how-to-avoid-them-a12f02345be5)._


#### _Reviewed by Temitayo Adeleke_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/users/show.html.erb
> +    <%# <%=f.submit "#{Friendship.request_confirmed(@user).size} Invite Sent"  %>
- _Remove commented code_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/users/show.html.erb
>        <%end%>
- _Remove logic from the view_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/users/_user.html.erb
>          <%end%>
- _Remove logic from the view_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/users/_user.html.erb
> +  <% unless current_user == user%>
- _Remove logic from the view_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/layouts/application.html.erb
>          <% if current_user%>
- _Remove logic from the view_

2020-12-17 19:21 UTC, lekegitrepo commented on app/views/friendships/index.html.erb
>  <%else%>
- _Remove logic from the view_

2020-12-18 08:43 UTC, peterrobert requested changes
### CHANGES REQUIRED 🛑 ♻️ 
Hello, @jrai0792  great progress. Good work implementing some of the changes as requested in the previous review. However, there are a few changes that need to be made. Kindly check below ⬇️ 

**logic in views**

- [ ] There are still a few remaining logic in your views. Kindly remember that all logic should be added to the helpers. I will try and name a few places that I have noticed.

1. In your invitations folder under the index.html.erb there is an if statement that is checking for the invitation status.
2.  In your user's folder in the user partial there is an unless condition.

- [ ] Just like stated in the previous review we can not have the new statement in the index method. If you check your posts controller you have this method ⬇️ 
`def index
    @post = Post.new
    timeline_posts
  end`

Instead of that ⬆️ 

create a new method like so ⬇️ 
`def new
  @post = Post.new

end
`
Kindly do those changes and submit your work for another review.

### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING 💻

2020-12-18 08:43 UTC, peterrobert commented on app/views/users/_user.html.erb
>  <%end%>
Kindly remove logic in your views. There should be no logic in your views. Kindly use helpers to remove all the logic in your views.
[Where do I put my code ](http://codefol.io/posts/Where-Do-I-Put-My-Code/)

2020-12-18 10:33 UTC, PhillipUg approved these changes
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this project approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

2020-12-18 10:34 UTC, merged